apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    strimzi.io/next-node-ids: "[0-2]"
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        kraftMetadata: shared
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    strimzi.io/next-node-ids: "[3-7]"
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        kraftMetadata: shared
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      # tunings to make cluster model generation faster
      cruise.control.metrics.reporter.metrics.reporting.interval.ms: 5000
      cruise.control.metrics.reporter.metadata.max.age.ms: 4000
      cruise.control.metrics.topic.replication.factor: 1
      cruise.control.metrics.topic.min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
  cruiseControl:
    autoRebalance:
      - mode: add-brokers
      - mode: remove-brokers
    brokerCapacity:
      inboundNetwork: 500MB/s
      outboundNetwork: 500MB/s
    config:
      # increase active user tasks
      max.active.user.tasks: 10
      # tunings to make cluster model generation faster
      metric.sampling.interval.ms: 5000
      cruise.control.metrics.reporter.metrics.reporting.interval.ms: 5000
      metadata.max.age.ms: 4000
      sample.store.topic.replication.factor: 1
      partition.sample.store.topic.partition.count: 1
      broker.sample.store.topic.partition.count: 1
      skip.sample.store.topic.rack.awareness.check: true
      partition.metrics.window.ms: 10000
      broker.metrics.window.ms: 10000
      monitor.state.update.interval.ms: 10000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
